import { Translation, Language } from './types';

// Registratsiya uchun Admin ID: 7777
export const ADMIN_ID = "7777"; 
// Bot xabarlari boradigan haqiqiy Telegram ID
export const BOT_ADMIN_ID = "8215056224";
export const BOT_TOKEN = "8543158894:AAHkaN83tLCgNrJ-Omutn744aTui784GScc";
export const CARD_NUMBER = "4073420067355457";
export const CARD_HOLDER = "Gulzebo Holboyeva";

export const translations: Record<Language, Translation> = {
  uz: {
    welcome: "Ruslan Marketga xush kelibsiz",
    login: "Kirish",
    enterId: "User IDingizni kiriting",
    enterPhone: "Telefon raqamingizni kiriting",
    start: "Boshlash",
    home: "Asosiy",
    trackers: "Treklar",
    profile: "Profil",
    settings: "Sozlamalar",
    addTrack: "Trek raqam qo'shish",
    trackPlaceholder: "Trek raqamini kiriting",
    invalidTrack: "Noto'g'ri trek raqami",
    stats: "Statistika",
    totalWeight: "Umumiy vazn",
    totalPaid: "Umumiy to'lov",
    tier: "Daraja",
    language: "Til",
    theme: "Mavzu",
    adminPanel: "Admin Panel",
    updateWeight: "Vazn va narxni yangilash",
    save: "Saqlash",
    pricePerKg: "1 kg narxi",
    loyaltyFriend: "Do'st",
    loyaltyDear: "Qadirdon",
    loyaltyPartner: "Hamkor",
    pay: "To'lov qilish",
    paymentDetails: "To'lov tafsilotlari",
    confirmPayment: "To'lovni tasdiqlash",
    awaitingVerification: "Tasdiqlash kutilmoqda",
  },
  ru: {
    welcome: "Добро пожаловать в Ruslan Market",
    login: "Вход",
    enterId: "Введите User ID",
    enterPhone: "Введите номер телефона",
    start: "Начать",
    home: "Главная",
    trackers: "Треки",
    profile: "Профиль",
    settings: "Настройки",
    addTrack: "Добавить трек",
    trackPlaceholder: "Введите трек номер",
    invalidTrack: "Неверный трек номер",
    stats: "Статистика",
    totalWeight: "Общий вес",
    totalPaid: "Общая сумма",
    tier: "Уровень",
    language: "Язык",
    theme: "Тема",
    adminPanel: "Админ панель",
    updateWeight: "Обновить вес и цену",
    save: "Сохранить",
    pricePerKg: "Цена за кг",
    loyaltyFriend: "Друг",
    loyaltyDear: "Дорогой",
    loyaltyPartner: "Партнер",
    pay: "Оплатить",
    paymentDetails: "Детали оплаты",
    confirmPayment: "Подтвердить оплату",
    awaitingVerification: "Ожидание проверки",
  },
  en: {
    welcome: "Welcome to Ruslan Market",
    login: "Login",
    enterId: "Enter User ID",
    enterPhone: "Enter Phone Number",
    start: "Start",
    home: "Home",
    trackers: "Tracks",
    profile: "Profile",
    settings: "Settings",
    addTrack: "Add Track",
    trackPlaceholder: "Enter track number",
    invalidTrack: "Invalid track number",
    stats: "Statistics",
    totalWeight: "Total Weight",
    totalPaid: "Total Paid",
    tier: "Tier",
    language: "Language",
    theme: "Theme",
    adminPanel: "Admin Panel",
    updateWeight: "Update weight & price",
    save: "Save",
    pricePerKg: "Price per kg",
    loyaltyFriend: "Friend",
    loyaltyDear: "Dear",
    loyaltyPartner: "Partner",
    pay: "Pay Now",
    paymentDetails: "Payment Details",
    confirmPayment: "Confirm Payment",
    awaitingVerification: "Awaiting Verification",
  }
};